### PR TITLE
p4lang/p4app:stable is not existed, change to latest

### PR DESCRIPTION
**Pull request by MaoJianwei**
p4lang/p4app:stable is not existed, change to latest

### CODE REVIEW

**Comment by MaoJianwei** [comment]
I got error message from docker with p4lang/p4app:stable,
and I have checked p4lang/p4app:latest works well.

**Comment by MaoJianwei** [comment]
could you please merge this request?

**Comment by theojepsen** [comment]
Is there a reason this was not merged? As it is now, `p4app update` is broken because it can't find "p4lang/p4app:stable". This PR would fix this.

**Comment by robertsoule-barefoot** [comment]
Hey Theo, I fixed this in a separate PR.

**Pull request merged**
