### PR TITLE
Add support for passing pcap files in stf test

### PR DESCRIPTION
**Pull request by tudang**
Hi @sethfowler,

In the stf test, I've added some code that allows users to pass raw packet data or a pcap file. I only tested with the Paxos example. However, with the change, running simple_router has a problem with Mininet.
```
P4APP_IMAGE=p4lang/p4app_test ~/workspace/p4app/p4app run examples/simple_router.p4app                                      
Entering build directory.
Extracting package.
Reading package manifest.
> p4c-bm2-ss --p4v 16 "simple_router.p4" -o "simple_router.p4.json"
> python2 "/scripts/mininet/single_switch_mininet.py" --log-file "/var/log/simple_router.p4.log" --cli-message "mininet_message.txt" --num-hosts 2 --switch-config "simple_router.config" --behavioral-exe "simple_switch" --json "simple_router.p4.json"
Adding host h1
Adding host h2
*** Error setting resource limits. Mininet's performance may be affected.
*** Creating network
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller

*** Starting 1 switches
s1 Starting P4 switch s1.
simple_switch -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 simple_router.p4.json --debugger --log-console
P4 switch s1 did not start correctly.
```

I'm not sure it's caused by my change or by environment setup. Could you test this on your side?

Cheers,

### CODE REVIEW

**Comment by sethfowler** [comment]
@tudang, I've been in the process of updating all of our Docker images to Ubuntu 16.04. It's possible that you've just gotten unlucky and happened to try this while things were in an inconsistent state. I am wrapping up that process now; once I finish up, I'll test your patch.

**Comment by sethfowler** [comment]
@tudang I haven't gotten a chance to try your patch yet, but just FYI, p4app was indeed temporarily busted and it should be fixed now. Run `p4app update` to get the newest Docker image. (Just rerunning `docker build` won't fix it because upstream Docker images have changed.) You should also update your checkout of this repo.

**Comment by tudang** [comment]
I pulled the update and my patch has no problem with the simple_router example anymore. It still works for Paxos example. I think it should be safe to merge now.

**Comment by sethfowler** [comment]
This is great! Thanks for putting it together, Tu.

**Pull request merged**
