### PR TITLE
Added an API for reading direct counters associated with a table in the p4 program

### PR DESCRIPTION
**Pull request by serhatarslan-hub**

### CODE REVIEW

**Comment by theojepsen** [comment]
@serhatarslan-hub This looks great! Thank you for adding this functionality.

Can you add a few lines of documentation to the [Reading Counters section of the README](https://github.com/p4lang/p4app/tree/rc-2.0.0#reading-counters)? Also, do you think you could extend [examples/counter.p4app](https://github.com/p4lang/p4app/blob/rc-2.0.0/examples/counter.p4app/main.py) with a direct counter in the data plane, and an example of how it's read from the control plane?

**Comment by serhatarslan-hub** [comment]
@theojepsen You can find the documentation and example on my last commit.

**Comment by theojepsen** [comment]
:+1: LGTM! Thank you @serhatarslan-hub

**Review by robertsoule — APPROVED** [review]
+1

**Pull request merged**
